# amcl_params.yaml

# Basic AMCL Parameters
min_particles: 500
max_particles: 3000
kld_err: 0.02
kld_z: 0.99
odom_model_type: "diff"
odom_alpha1: 0.1
odom_alpha2: 0.1
odom_alpha3: 0.1
odom_alpha4: 0.1
odom_alpha5: 0.1
odom_frame_id: odom
base_frame_id: base_footprint

# Laser Parameters
laser_model_type: "likelihood_field"
laser_likelihood_max_dist: 2.0
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_max_beams: 180
laser_max_range: 3.5

# Initial pose and covariance
initial_pose_x: 0.5
initial_pose_y: 4.0
initial_pose_a: -1.0
initial_cov_xx: 0.5
initial_cov_yy: 0.5
initial_cov_aa: 0.2

# Update thresholds
update_min_d: 0.2
update_min_a: 0.2
resample_interval: 1
transfrom_tolerance: 0.5
recovery_alpha_slow: 0.00
recovery_alpha_fast: 0.00
gui_publish_rate: 50.0

