DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 3.0
  min_vel_x: -3.0

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  2.0
  min_vel_trans:  -2.0

  max_vel_theta: 6.0
  min_vel_theta: -3.0

  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 6.0 

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 3.0
  vx_samples: 20
  vy_samples: 0
  vth_samples: 50
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 10.0
  goal_distance_bias: 30.0
  occdist_scale: 0.05
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  
  # Additional Parameters
  heading_lookahead: 0.8
  heading_scoring: true
  heading_scoring_timestep: 1.0


# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
