global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.6
  
  static_map: false
  rolling_window: false
  
  track_unknown_space: true
  width: 5
  height: 5
  
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: map
    subscribe_to_updates: true
  
