local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 1.0
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.05
  track_unknown_space: false

