#move_base

shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 3.0
conservative_reset_dist: 3.0
planner_frequency: 10.0
oscillation_timeout: 6.0
oscillation_distance: 0.4


recovery_behaviors:
  - name: 'clear'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate'
    type: 'rotate_recovery/RotateRecovery'

