footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
robot_radius: 0.17


obstacle_layer:
  observation_sources: scan
  scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
  obstacle_range: 2.5
  raytrace_range: 3.0
  max_obstacle_height: 0.6

inflation_layer:
  inflation_radius: 0.55
  cost_scaling_factor: 10.0


