DWAPlannerROS:
# Robot Configuration Parameters
  max_vel_x: 0.6
  min_vel_x: -0.6
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_trans_vel: 0.6
  min_trans_vel: 0.1
  max_rot_vel: 6.0
  min_rot_vel: -6.0
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  acc_lim_y: 0.0
  holonomic_robot: false
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false
  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 6
  vy_samples: 1
  vtheta_samples: 20
  meter_scoring: true
  controller_frequency: 20.0
  publish_cost_grid_pc: true
  oscillation_reset_dist: 0.05
  prune_plan: true

# Trajectory Scoring Parameters
  path_distance_bias: 10.0
  goal_distance_bias: 30.0
  occdist_scale: 0.005
  forward_point_distance: 0.325
  stop_time_buffer: 0.1
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  
  # Additional Parameters
  heading_lookahead: 2.0
  heading_scoring: false
  heading_scoring_timestep: 1.0

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
